apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: skaffold-demo
build:
  local:
    push: false
  artifacts:
    - image: localhost/go-test
      docker:
        dockerfile: Dockerfile
      hooks:
        after:
          - command: ["sh", "-c", "./skaffold-hooks/post-build.sh"]
manifests:
  rawYaml:
    - k8s.yml
deploy:
  kubectl:
    defaultNamespace: "default"
    hooks:
      before:
        - host:
            command: ["sh", "-c", "./skaffold-hooks/pre-deploy.sh"]
